name: GitHub Actions Demo

on:
  push:
    branches:
      - main
    paths-ignore: 
      - .github/**
  pull_request:
    branches:
      - main
  schedule:
    - cron: '15 6 * * 0'
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: print Event name
        run: echo ${{ github.event_name }}

      - name: print Branch name
        run: echo ${{ github.ref_name }}

      - uses: actions/checkout@v3.3.0
      - name: print file list
        run: echo $(ls -l ./*)
    
